#!/bin/bash

### Startup ###
sxhkd &

# Monitors
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 2560x1440 --rotate normal --right-of eDP1


### BSPWM Config ###
bspc config border_width    0
bspc config window_gap      0
bspc config split_ratio     0.50

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI-1-0 -d VI VII VII IX X